dist: trusty
language: node_js
cache: yarn
node_js:
- '6.10'
- '7'
- '8'
install:
- yarn install --frozen-lockfile
before_install:
# Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.25.4
- export PATH=$HOME/.yarn/bin:$PATH
before_script:
- yarn bootstrap
script:
- yarn lint
- yarn test
