dist: trusty
language: node_js
cache: yarn
node_js:
- '6'
- '7'
- '8'
before_install:
# oao breaks on node 6 for anything newer than yarn 0.28.4:
# https://github.com/guigrpa/oao/issues/51
- curl -sSfL https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --frozen-lockfile
before_script:
- yarn bootstrap
script:
- yarn lint
- yarn test
