dist: trusty
language: node_js
cache: yarn
node_js:
- '6.10'
- '7'
- '8'
install:
- yarn install --frozen-lockfile
before_script:
- yarn bootstrap -- --frozen-lockfile
script:
- yarn lint
- yarn test
