docs_dir: 'docs'
site_dir: 'build'
strict: true

site_name: 'Neutrino'
site_description: 'Create and build modern JavaScript applications with zero initial configuration'
repo_name: 'mozilla-neutrino/neutrino-dev'
repo_url: 'https://github.com/mozilla-neutrino/neutrino-dev'

# https://squidfunk.github.io/mkdocs-material/getting-started/#configuration
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  # Disable the default top left logo until we sort out our custom one.
  logo:
    icon: ' '

# http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
pages:
  - Introduction: './index.md'
  - Getting Started:
    - Installation: './installation/index.md'
    - Create new project: './installation/create-new-project.md'
  - Usage: './usage.md'
  - Project Layout: './project-layout.md'
  - FAQ: './FAQ.md'
  - Learning Resources: './learning-resources.md'
  - CLI: './cli.md'
  - API: './api.md'
  - Configuration API - webpack-chain: './webpack-chain.md'
  - Customization: './customization.md'
  - Creating Presets: './creating-presets.md'
  - Migration Guide: './migration-guide.md'
  - Presets: './presets.md'
  - Middleware: './middleware.md'
  - Packages:
    - Web: './packages/web.md'
    - React: './packages/react.md'
    - Preact: './packages/preact.md'
    - Vue: './packages/vue.md'
    - Node.js: './packages/node.md'
    - Library: './packages/library.md'
    - React Components: './packages/react-components.md'
    - Airbnb: './packages/airbnb.md'
    - Airbnb Base: './packages/airbnb-base.md'
    - StandardJS: './packages/standardjs.md'
    - Karma: './packages/karma.md'
    - Mocha: './packages/mocha.md'
    - Jest: './packages/jest.md'
    - banner: './packages/banner.md'
    - clean: './packages/clean.md'
    - compile-loader: './packages/compile-loader.md'
    - copy: './packages/copy.md'
    - dev-server: './packages/dev-server.md'
    - env: './packages/env.md'
    - eslint: './packages/eslint.md'
    - font-loader: './packages/font-loader.md'
    - hot: './packages/hot.md'
    - html-loader: './packages/html-loader.md'
    - html-template: './packages/html-template.md'
    - image-loader: './packages/image-loader.md'
    - image-minify: './packages/image-minify.md'
    - loader-merge: './packages/loader-merge.md'
    - pwa: './packages/pwa.md'
    - start-server: './packages/start-server.md'
    - style-loader: './packages/style-loader.md'
    - style-minify: './packages/style-minify.md'
    - stylelint: './packages/stylelint.md'
  # External links aren't supported in the sidebar, so we link to a
  # blank page that has a corresponding redirect in netlify.toml.
  - v8 Documentation: './v8.md'
  - v7 Documentation: './v7.md'
  - v6 Documentation: './v6.md'
  - v5 Documentation: './v5.md'
  - v4 Documentation: './v4.md'
  - Contributing:
    - Overview: './contributing/index.md'
    - Development Process: './contributing/development.md'
    - Code of Conduct: './contributing/code-of-conduct.md'

# https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
